'use client'
// import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Navbar from "./_navbar/page";
import { Provider } from "react-redux";
import { store } from "./_redux/store";
import { Toaster } from "react-hot-toast";
import { Container } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Socail-Media",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Provider store={store}>
      
          <AppRouterCacheProvider>
            
        <Navbar/>
            <Container maxWidth='sm' sx={{mt:7}} >
          {children}
          <Toaster/>
          </Container>
        </AppRouterCacheProvider>

       </Provider>
      </body>
    </html>
  );
}
